fix: cleanup: .tmp/my-avbroot-setup needs to be deleted
my-avbroot-setup needs to be deleted even if SKIP_CLEANUP=true:

ERROR: Could not open requirements file: [Errno 2] No such file or
directory: '.tmp/my-avbroot-setup/requirements.txt'